version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: ms-client-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clientdb
      MYSQL_USER: devsu
      MYSQL_PASSWORD: devsu123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Microservicio de Clientes
  ms-java-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-java-client
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8081
      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "8082:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ms-network
    restart: unless-stopped

networks:
  ms-network:
    driver: bridge

volumes:
  mysql-data:
