version: '3.8'

services:
  # Base de datos MySQL para Clientes
  mysql-client:
    image: mysql:8.0
    container_name: ms-client-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clientdb
      MYSQL_USER: devsu
      MYSQL_PASSWORD: devsu123
    ports:
      - "3307:3306"
    volumes:
      - mysql-client-data:/var/lib/mysql
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Base de datos MySQL para Cuentas
  mysql-account:
    image: mysql:8.0
    container_name: ms-account-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: accountdb
      MYSQL_USER: devsu
      MYSQL_PASSWORD: devsu123
    ports:
      - "3308:3306"
    volumes:
      - mysql-account-data:/var/lib/mysql
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Microservicio de Clientes
  ms-java-client:
    build:
      context: ./ms-java-client
      dockerfile: Dockerfile
    container_name: ms-java-client
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-client:3306/clientdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8081
      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "8082:8081"
    depends_on:
      mysql-client:
        condition: service_healthy
    networks:
      - ms-network
    restart: unless-stopped

  # Microservicio de Cuentas
  ms-java-account:
    build:
      context: ./ms-java-account
      dockerfile: Dockerfile
    container_name: ms-java-account
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-account:3306/accountdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "8081:8080"
    depends_on:
      mysql-account:
        condition: service_healthy
    networks:
      - ms-network
    restart: unless-stopped

networks:
  ms-network:
    driver: bridge

volumes:
  mysql-client-data:
  mysql-account-data:
